// Code generated by "go generate". Please don't change this file directly.

package backupsearch

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// SearchResultExportJob_S3ExportSpecification AWS CloudFormation Resource (AWS::BackupSearch::SearchResultExportJob.S3ExportSpecification)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-backupsearch-searchresultexportjob-s3exportspecification.html
type SearchResultExportJob_S3ExportSpecification struct {

	// DestinationBucket AWS CloudFormation Property
	// Required: true
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-backupsearch-searchresultexportjob-s3exportspecification.html#cfn-backupsearch-searchresultexportjob-s3exportspecification-destinationbucket
	DestinationBucket string `json:"DestinationBucket"`

	// DestinationPrefix AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-backupsearch-searchresultexportjob-s3exportspecification.html#cfn-backupsearch-searchresultexportjob-s3exportspecification-destinationprefix
	DestinationPrefix *string `json:"DestinationPrefix,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *SearchResultExportJob_S3ExportSpecification) AWSCloudFormationType() string {
	return "AWS::BackupSearch::SearchResultExportJob.S3ExportSpecification"
}
