// Code generated by "go generate". Please don't change this file directly.

package backupsearch

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// SearchResultExportJob_ExportSpecification AWS CloudFormation Resource (AWS::BackupSearch::SearchResultExportJob.ExportSpecification)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-backupsearch-searchresultexportjob-exportspecification.html
type SearchResultExportJob_ExportSpecification struct {

	// S3ExportSpecification AWS CloudFormation Property
	// Required: true
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-backupsearch-searchresultexportjob-exportspecification.html#cfn-backupsearch-searchresultexportjob-exportspecification-s3exportspecification
	S3ExportSpecification *SearchResultExportJob_S3ExportSpecification `json:"S3ExportSpecification"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *SearchResultExportJob_ExportSpecification) AWSCloudFormationType() string {
	return "AWS::BackupSearch::SearchResultExportJob.ExportSpecification"
}
