// Code generated by "go generate". Please don't change this file directly.

package quicksight

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// KnowledgeBase_MediaExtractionConfiguration AWS CloudFormation Resource (AWS::QuickSight::KnowledgeBase.MediaExtractionConfiguration)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-quicksight-knowledgebase-mediaextractionconfiguration.html
type KnowledgeBase_MediaExtractionConfiguration struct {

	// AudioExtractionConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-quicksight-knowledgebase-mediaextractionconfiguration.html#cfn-quicksight-knowledgebase-mediaextractionconfiguration-audioextractionconfiguration
	AudioExtractionConfiguration *KnowledgeBase_AudioExtractionConfiguration `json:"AudioExtractionConfiguration,omitempty"`

	// ImageExtractionConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-quicksight-knowledgebase-mediaextractionconfiguration.html#cfn-quicksight-knowledgebase-mediaextractionconfiguration-imageextractionconfiguration
	ImageExtractionConfiguration *KnowledgeBase_ImageExtractionConfiguration `json:"ImageExtractionConfiguration,omitempty"`

	// VideoExtractionConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-quicksight-knowledgebase-mediaextractionconfiguration.html#cfn-quicksight-knowledgebase-mediaextractionconfiguration-videoextractionconfiguration
	VideoExtractionConfiguration *KnowledgeBase_VideoExtractionConfiguration `json:"VideoExtractionConfiguration,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *KnowledgeBase_MediaExtractionConfiguration) AWSCloudFormationType() string {
	return "AWS::QuickSight::KnowledgeBase.MediaExtractionConfiguration"
}
