// Code generated by "go generate". Please don't change this file directly.

package agentregistry

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// RegistryRecord_Descriptors AWS CloudFormation Resource (AWS::AgentRegistry::RegistryRecord.Descriptors)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-descriptors.html
type RegistryRecord_Descriptors struct {

	// A2aAgentCard AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-descriptors.html#cfn-agentregistry-registryrecord-descriptors-a2aagentcard
	A2aAgentCard *RegistryRecord_A2aAgentCardDescriptor `json:"A2aAgentCard,omitempty"`

	// AgentSkillsDefinition AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-descriptors.html#cfn-agentregistry-registryrecord-descriptors-agentskillsdefinition
	AgentSkillsDefinition *RegistryRecord_AgentSkillsDefinitionDescriptor `json:"AgentSkillsDefinition,omitempty"`

	// Agui AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-descriptors.html#cfn-agentregistry-registryrecord-descriptors-agui
	Agui *RegistryRecord_AgUiDescriptor `json:"Agui,omitempty"`

	// Custom AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-descriptors.html#cfn-agentregistry-registryrecord-descriptors-custom
	Custom *RegistryRecord_CustomDescriptor `json:"Custom,omitempty"`

	// Http AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-descriptors.html#cfn-agentregistry-registryrecord-descriptors-http
	Http *RegistryRecord_HttpDescriptor `json:"Http,omitempty"`

	// McpServer AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-agentregistry-registryrecord-descriptors.html#cfn-agentregistry-registryrecord-descriptors-mcpserver
	McpServer *RegistryRecord_McpServerDescriptor `json:"McpServer,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *RegistryRecord_Descriptors) AWSCloudFormationType() string {
	return "AWS::AgentRegistry::RegistryRecord.Descriptors"
}
