// Code generated by "go generate". Please don't change this file directly.

package mediatailor

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// PrefetchSchedule_RecurringConsumption AWS CloudFormation Resource (AWS::MediaTailor::PrefetchSchedule.RecurringConsumption)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-mediatailor-prefetchschedule-recurringconsumption.html
type PrefetchSchedule_RecurringConsumption struct {

	// AvailMatchingCriteria AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-mediatailor-prefetchschedule-recurringconsumption.html#cfn-mediatailor-prefetchschedule-recurringconsumption-availmatchingcriteria
	AvailMatchingCriteria []PrefetchSchedule_AvailMatchingCriteria `json:"AvailMatchingCriteria,omitempty"`

	// RetrievedAdExpirationSeconds AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-mediatailor-prefetchschedule-recurringconsumption.html#cfn-mediatailor-prefetchschedule-recurringconsumption-retrievedadexpirationseconds
	RetrievedAdExpirationSeconds *int `json:"RetrievedAdExpirationSeconds,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *PrefetchSchedule_RecurringConsumption) AWSCloudFormationType() string {
	return "AWS::MediaTailor::PrefetchSchedule.RecurringConsumption"
}
