// Code generated by "go generate". Please don't change this file directly.

package cleanrooms

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// IntermediateTable_DifferentialPrivacy AWS CloudFormation Resource (AWS::CleanRooms::IntermediateTable.DifferentialPrivacy)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cleanrooms-intermediatetable-differentialprivacy.html
type IntermediateTable_DifferentialPrivacy struct {

	// Columns AWS CloudFormation Property
	// Required: true
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cleanrooms-intermediatetable-differentialprivacy.html#cfn-cleanrooms-intermediatetable-differentialprivacy-columns
	Columns []IntermediateTable_DifferentialPrivacyColumn `json:"Columns"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *IntermediateTable_DifferentialPrivacy) AWSCloudFormationType() string {
	return "AWS::CleanRooms::IntermediateTable.DifferentialPrivacy"
}
