// Code generated by "go generate". Please don't change this file directly.

package servicequotas

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// Quota_MetricInfo AWS CloudFormation Resource (AWS::ServiceQuotas::Quota.MetricInfo)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-servicequotas-quota-metricinfo.html
type Quota_MetricInfo struct {

	// MetricDimensions AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-servicequotas-quota-metricinfo.html#cfn-servicequotas-quota-metricinfo-metricdimensions
	MetricDimensions map[string]string `json:"MetricDimensions,omitempty"`

	// MetricName AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-servicequotas-quota-metricinfo.html#cfn-servicequotas-quota-metricinfo-metricname
	MetricName *string `json:"MetricName,omitempty"`

	// MetricNamespace AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-servicequotas-quota-metricinfo.html#cfn-servicequotas-quota-metricinfo-metricnamespace
	MetricNamespace *string `json:"MetricNamespace,omitempty"`

	// MetricStatisticRecommendation AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-servicequotas-quota-metricinfo.html#cfn-servicequotas-quota-metricinfo-metricstatisticrecommendation
	MetricStatisticRecommendation *string `json:"MetricStatisticRecommendation,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *Quota_MetricInfo) AWSCloudFormationType() string {
	return "AWS::ServiceQuotas::Quota.MetricInfo"
}
