// Code generated by "go generate". Please don't change this file directly.

package lambda

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// CapacityProvider_CapacityProviderTelemetryConfig AWS CloudFormation Resource (AWS::Lambda::CapacityProvider.CapacityProviderTelemetryConfig)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-capacityprovider-capacityprovidertelemetryconfig.html
type CapacityProvider_CapacityProviderTelemetryConfig struct {

	// LoggingConfig AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-capacityprovider-capacityprovidertelemetryconfig.html#cfn-lambda-capacityprovider-capacityprovidertelemetryconfig-loggingconfig
	LoggingConfig *CapacityProvider_CapacityProviderLoggingConfig `json:"LoggingConfig,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *CapacityProvider_CapacityProviderTelemetryConfig) AWSCloudFormationType() string {
	return "AWS::Lambda::CapacityProvider.CapacityProviderTelemetryConfig"
}
