// Code generated by "go generate". Please don't change this file directly.

package lambda

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// Function_LambdaManagedInstancesCapacityProviderConfig AWS CloudFormation Resource (AWS::Lambda::Function.LambdaManagedInstancesCapacityProviderConfig)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-lambdamanagedinstancescapacityproviderconfig.html
type Function_LambdaManagedInstancesCapacityProviderConfig struct {

	// CapacityProviderArn AWS CloudFormation Property
	// Required: true
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-lambdamanagedinstancescapacityproviderconfig.html#cfn-lambda-function-lambdamanagedinstancescapacityproviderconfig-capacityproviderarn
	CapacityProviderArn string `json:"CapacityProviderArn"`

	// ExecutionEnvironmentMemoryGiBPerVCpu AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-lambdamanagedinstancescapacityproviderconfig.html#cfn-lambda-function-lambdamanagedinstancescapacityproviderconfig-executionenvironmentmemorygibpervcpu
	ExecutionEnvironmentMemoryGiBPerVCpu *float64 `json:"ExecutionEnvironmentMemoryGiBPerVCpu,omitempty"`

	// PerExecutionEnvironmentMaxConcurrency AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-lambdamanagedinstancescapacityproviderconfig.html#cfn-lambda-function-lambdamanagedinstancescapacityproviderconfig-perexecutionenvironmentmaxconcurrency
	PerExecutionEnvironmentMaxConcurrency *int `json:"PerExecutionEnvironmentMaxConcurrency,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *Function_LambdaManagedInstancesCapacityProviderConfig) AWSCloudFormationType() string {
	return "AWS::Lambda::Function.LambdaManagedInstancesCapacityProviderConfig"
}
