// Code generated by "go generate". Please don't change this file directly.

package ec2

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// ExportInstanceTask_ExportToS3Task AWS CloudFormation Resource (AWS::EC2::ExportInstanceTask.ExportToS3Task)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-exportinstancetask-exporttos3task.html
type ExportInstanceTask_ExportToS3Task struct {

	// ContainerFormat AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-exportinstancetask-exporttos3task.html#cfn-ec2-exportinstancetask-exporttos3task-containerformat
	ContainerFormat *string `json:"ContainerFormat,omitempty"`

	// DiskImageFormat AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-exportinstancetask-exporttos3task.html#cfn-ec2-exportinstancetask-exporttos3task-diskimageformat
	DiskImageFormat *string `json:"DiskImageFormat,omitempty"`

	// S3Bucket AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-exportinstancetask-exporttos3task.html#cfn-ec2-exportinstancetask-exporttos3task-s3bucket
	S3Bucket *string `json:"S3Bucket,omitempty"`

	// S3Key AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-exportinstancetask-exporttos3task.html#cfn-ec2-exportinstancetask-exporttos3task-s3key
	S3Key *string `json:"S3Key,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *ExportInstanceTask_ExportToS3Task) AWSCloudFormationType() string {
	return "AWS::EC2::ExportInstanceTask.ExportToS3Task"
}
