// Code generated by "go generate". Please don't change this file directly.

package transcribe

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// TranscriptionJob_Subtitles AWS CloudFormation Resource (AWS::Transcribe::TranscriptionJob.Subtitles)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-transcribe-transcriptionjob-subtitles.html
type TranscriptionJob_Subtitles struct {

	// Formats AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-transcribe-transcriptionjob-subtitles.html#cfn-transcribe-transcriptionjob-subtitles-formats
	Formats []string `json:"Formats,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *TranscriptionJob_Subtitles) AWSCloudFormationType() string {
	return "AWS::Transcribe::TranscriptionJob.Subtitles"
}
