// Code generated by "go generate". Please don't change this file directly.

package mediapackagev2

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// HarvestJob_S3DestinationConfig AWS CloudFormation Resource (AWS::MediaPackageV2::HarvestJob.S3DestinationConfig)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-mediapackagev2-harvestjob-s3destinationconfig.html
type HarvestJob_S3DestinationConfig struct {

	// BucketName AWS CloudFormation Property
	// Required: true
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-mediapackagev2-harvestjob-s3destinationconfig.html#cfn-mediapackagev2-harvestjob-s3destinationconfig-bucketname
	BucketName string `json:"BucketName"`

	// DestinationPath AWS CloudFormation Property
	// Required: true
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-mediapackagev2-harvestjob-s3destinationconfig.html#cfn-mediapackagev2-harvestjob-s3destinationconfig-destinationpath
	DestinationPath string `json:"DestinationPath"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *HarvestJob_S3DestinationConfig) AWSCloudFormationType() string {
	return "AWS::MediaPackageV2::HarvestJob.S3DestinationConfig"
}
