// Code generated by "go generate". Please don't change this file directly.

package bedrockagentcore

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// Harness_HarnessModelConfiguration AWS CloudFormation Resource (AWS::BedrockAgentCore::Harness.HarnessModelConfiguration)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-bedrockagentcore-harness-harnessmodelconfiguration.html
type Harness_HarnessModelConfiguration struct {

	// BedrockModelConfig AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-bedrockagentcore-harness-harnessmodelconfiguration.html#cfn-bedrockagentcore-harness-harnessmodelconfiguration-bedrockmodelconfig
	BedrockModelConfig *Harness_HarnessBedrockModelConfig `json:"BedrockModelConfig,omitempty"`

	// GeminiModelConfig AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-bedrockagentcore-harness-harnessmodelconfiguration.html#cfn-bedrockagentcore-harness-harnessmodelconfiguration-geminimodelconfig
	GeminiModelConfig *Harness_HarnessGeminiModelConfig `json:"GeminiModelConfig,omitempty"`

	// LiteLlmModelConfig AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-bedrockagentcore-harness-harnessmodelconfiguration.html#cfn-bedrockagentcore-harness-harnessmodelconfiguration-litellmmodelconfig
	LiteLlmModelConfig *Harness_HarnessLiteLlmModelConfig `json:"LiteLlmModelConfig,omitempty"`

	// OpenAiModelConfig AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-bedrockagentcore-harness-harnessmodelconfiguration.html#cfn-bedrockagentcore-harness-harnessmodelconfiguration-openaimodelconfig
	OpenAiModelConfig *Harness_HarnessOpenAiModelConfig `json:"OpenAiModelConfig,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *Harness_HarnessModelConfiguration) AWSCloudFormationType() string {
	return "AWS::BedrockAgentCore::Harness.HarnessModelConfiguration"
}
