// Code generated by "go generate". Please don't change this file directly.

package stepfunctions

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// MapRun_MapRunExecutionCounts AWS CloudFormation Resource (AWS::StepFunctions::MapRun.MapRunExecutionCounts)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-maprun-maprunexecutioncounts.html
type MapRun_MapRunExecutionCounts struct {

	// Aborted AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-maprun-maprunexecutioncounts.html#cfn-stepfunctions-maprun-maprunexecutioncounts-aborted
	Aborted *int `json:"Aborted,omitempty"`

	// Failed AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-maprun-maprunexecutioncounts.html#cfn-stepfunctions-maprun-maprunexecutioncounts-failed
	Failed *int `json:"Failed,omitempty"`

	// FailuresNotRedrivable AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-maprun-maprunexecutioncounts.html#cfn-stepfunctions-maprun-maprunexecutioncounts-failuresnotredrivable
	FailuresNotRedrivable *int `json:"FailuresNotRedrivable,omitempty"`

	// Pending AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-maprun-maprunexecutioncounts.html#cfn-stepfunctions-maprun-maprunexecutioncounts-pending
	Pending *int `json:"Pending,omitempty"`

	// PendingRedrive AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-maprun-maprunexecutioncounts.html#cfn-stepfunctions-maprun-maprunexecutioncounts-pendingredrive
	PendingRedrive *int `json:"PendingRedrive,omitempty"`

	// ResultsWritten AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-maprun-maprunexecutioncounts.html#cfn-stepfunctions-maprun-maprunexecutioncounts-resultswritten
	ResultsWritten *int `json:"ResultsWritten,omitempty"`

	// Running AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-maprun-maprunexecutioncounts.html#cfn-stepfunctions-maprun-maprunexecutioncounts-running
	Running *int `json:"Running,omitempty"`

	// Succeeded AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-maprun-maprunexecutioncounts.html#cfn-stepfunctions-maprun-maprunexecutioncounts-succeeded
	Succeeded *int `json:"Succeeded,omitempty"`

	// TimedOut AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-maprun-maprunexecutioncounts.html#cfn-stepfunctions-maprun-maprunexecutioncounts-timedout
	TimedOut *int `json:"TimedOut,omitempty"`

	// Total AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-maprun-maprunexecutioncounts.html#cfn-stepfunctions-maprun-maprunexecutioncounts-total
	Total *int `json:"Total,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *MapRun_MapRunExecutionCounts) AWSCloudFormationType() string {
	return "AWS::StepFunctions::MapRun.MapRunExecutionCounts"
}
