// Code generated by "go generate". Please don't change this file directly.

package omics

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// ReadSet_ETag AWS CloudFormation Resource (AWS::Omics::ReadSet.ETag)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-omics-readset-etag.html
type ReadSet_ETag struct {

	// Algorithm AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-omics-readset-etag.html#cfn-omics-readset-etag-algorithm
	Algorithm *string `json:"Algorithm,omitempty"`

	// Source1 AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-omics-readset-etag.html#cfn-omics-readset-etag-source1
	Source1 *string `json:"Source1,omitempty"`

	// Source2 AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-omics-readset-etag.html#cfn-omics-readset-etag-source2
	Source2 *string `json:"Source2,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *ReadSet_ETag) AWSCloudFormationType() string {
	return "AWS::Omics::ReadSet.ETag"
}
