// Code generated by "go generate". Please don't change this file directly.

package inspectorv2

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// CodeSecurityIntegration_CreateDetails AWS CloudFormation Resource (AWS::InspectorV2::CodeSecurityIntegration.CreateDetails)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-inspectorv2-codesecurityintegration-createdetails.html
type CodeSecurityIntegration_CreateDetails struct {

	// GitlabSelfManaged AWS CloudFormation Property
	// Required: true
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-inspectorv2-codesecurityintegration-createdetails.html#cfn-inspectorv2-codesecurityintegration-createdetails-gitlabselfmanaged
	GitlabSelfManaged *CodeSecurityIntegration_CreateGitLabSelfManagedIntegrationDetail `json:"GitlabSelfManaged"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *CodeSecurityIntegration_CreateDetails) AWSCloudFormationType() string {
	return "AWS::InspectorV2::CodeSecurityIntegration.CreateDetails"
}
