// Code generated by "go generate". Please don't change this file directly.

package macie2

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// ClassificationJob_S3JobDefinition AWS CloudFormation Resource (AWS::Macie2::ClassificationJob.S3JobDefinition)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-macie2-classificationjob-s3jobdefinition.html
type ClassificationJob_S3JobDefinition struct {

	// BucketDefinitions AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-macie2-classificationjob-s3jobdefinition.html#cfn-macie2-classificationjob-s3jobdefinition-bucketdefinitions
	BucketDefinitions []ClassificationJob_S3BucketDefinitionForJob `json:"BucketDefinitions,omitempty"`

	// Scoping AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-macie2-classificationjob-s3jobdefinition.html#cfn-macie2-classificationjob-s3jobdefinition-scoping
	Scoping interface{} `json:"Scoping,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *ClassificationJob_S3JobDefinition) AWSCloudFormationType() string {
	return "AWS::Macie2::ClassificationJob.S3JobDefinition"
}
