// Code generated by "go generate". Please don't change this file directly.

package wisdom

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// AIAgent_AIAgentConfiguration AWS CloudFormation Resource (AWS::Wisdom::AIAgent.AIAgentConfiguration)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wisdom-aiagent-aiagentconfiguration.html
type AIAgent_AIAgentConfiguration struct {

	// AnswerRecommendationAIAgentConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wisdom-aiagent-aiagentconfiguration.html#cfn-wisdom-aiagent-aiagentconfiguration-answerrecommendationaiagentconfiguration
	AnswerRecommendationAIAgentConfiguration *AIAgent_AnswerRecommendationAIAgentConfiguration `json:"AnswerRecommendationAIAgentConfiguration,omitempty"`

	// CaseSummarizationAIAgentConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wisdom-aiagent-aiagentconfiguration.html#cfn-wisdom-aiagent-aiagentconfiguration-casesummarizationaiagentconfiguration
	CaseSummarizationAIAgentConfiguration *AIAgent_CaseSummarizationAIAgentConfiguration `json:"CaseSummarizationAIAgentConfiguration,omitempty"`

	// EmailGenerativeAnswerAIAgentConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wisdom-aiagent-aiagentconfiguration.html#cfn-wisdom-aiagent-aiagentconfiguration-emailgenerativeansweraiagentconfiguration
	EmailGenerativeAnswerAIAgentConfiguration *AIAgent_EmailGenerativeAnswerAIAgentConfiguration `json:"EmailGenerativeAnswerAIAgentConfiguration,omitempty"`

	// EmailOverviewAIAgentConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wisdom-aiagent-aiagentconfiguration.html#cfn-wisdom-aiagent-aiagentconfiguration-emailoverviewaiagentconfiguration
	EmailOverviewAIAgentConfiguration *AIAgent_EmailOverviewAIAgentConfiguration `json:"EmailOverviewAIAgentConfiguration,omitempty"`

	// EmailResponseAIAgentConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wisdom-aiagent-aiagentconfiguration.html#cfn-wisdom-aiagent-aiagentconfiguration-emailresponseaiagentconfiguration
	EmailResponseAIAgentConfiguration *AIAgent_EmailResponseAIAgentConfiguration `json:"EmailResponseAIAgentConfiguration,omitempty"`

	// ManualSearchAIAgentConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wisdom-aiagent-aiagentconfiguration.html#cfn-wisdom-aiagent-aiagentconfiguration-manualsearchaiagentconfiguration
	ManualSearchAIAgentConfiguration *AIAgent_ManualSearchAIAgentConfiguration `json:"ManualSearchAIAgentConfiguration,omitempty"`

	// NoteTakingAIAgentConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wisdom-aiagent-aiagentconfiguration.html#cfn-wisdom-aiagent-aiagentconfiguration-notetakingaiagentconfiguration
	NoteTakingAIAgentConfiguration *AIAgent_NoteTakingAIAgentConfiguration `json:"NoteTakingAIAgentConfiguration,omitempty"`

	// OrchestrationAIAgentConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wisdom-aiagent-aiagentconfiguration.html#cfn-wisdom-aiagent-aiagentconfiguration-orchestrationaiagentconfiguration
	OrchestrationAIAgentConfiguration *AIAgent_OrchestrationAIAgentConfiguration `json:"OrchestrationAIAgentConfiguration,omitempty"`

	// SelfServiceAIAgentConfiguration AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-wisdom-aiagent-aiagentconfiguration.html#cfn-wisdom-aiagent-aiagentconfiguration-selfserviceaiagentconfiguration
	SelfServiceAIAgentConfiguration *AIAgent_SelfServiceAIAgentConfiguration `json:"SelfServiceAIAgentConfiguration,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *AIAgent_AIAgentConfiguration) AWSCloudFormationType() string {
	return "AWS::Wisdom::AIAgent.AIAgentConfiguration"
}
