// Code generated by "go generate". Please don't change this file directly.

package sagemaker

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// OptimizationJob_OptimizationJobOutputConfig AWS CloudFormation Resource (AWS::SageMaker::OptimizationJob.OptimizationJobOutputConfig)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-optimizationjob-optimizationjoboutputconfig.html
type OptimizationJob_OptimizationJobOutputConfig struct {

	// KmsKeyId AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-optimizationjob-optimizationjoboutputconfig.html#cfn-sagemaker-optimizationjob-optimizationjoboutputconfig-kmskeyid
	KmsKeyId *string `json:"KmsKeyId,omitempty"`

	// S3OutputLocation AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-optimizationjob-optimizationjoboutputconfig.html#cfn-sagemaker-optimizationjob-optimizationjoboutputconfig-s3outputlocation
	S3OutputLocation *string `json:"S3OutputLocation,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *OptimizationJob_OptimizationJobOutputConfig) AWSCloudFormationType() string {
	return "AWS::SageMaker::OptimizationJob.OptimizationJobOutputConfig"
}
