// Code generated by "go generate". Please don't change this file directly.

package sagemaker

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// Algorithm_InferenceSpecification AWS CloudFormation Resource (AWS::SageMaker::Algorithm.InferenceSpecification)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-algorithm-inferencespecification.html
type Algorithm_InferenceSpecification struct {

	// Containers AWS CloudFormation Property
	// Required: true
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-algorithm-inferencespecification.html#cfn-sagemaker-algorithm-inferencespecification-containers
	Containers []Algorithm_ModelPackageContainerDefinition `json:"Containers"`

	// SupportedContentTypes AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-algorithm-inferencespecification.html#cfn-sagemaker-algorithm-inferencespecification-supportedcontenttypes
	SupportedContentTypes []string `json:"SupportedContentTypes,omitempty"`

	// SupportedRealtimeInferenceInstanceTypes AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-algorithm-inferencespecification.html#cfn-sagemaker-algorithm-inferencespecification-supportedrealtimeinferenceinstancetypes
	SupportedRealtimeInferenceInstanceTypes []string `json:"SupportedRealtimeInferenceInstanceTypes,omitempty"`

	// SupportedResponseMIMETypes AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-algorithm-inferencespecification.html#cfn-sagemaker-algorithm-inferencespecification-supportedresponsemimetypes
	SupportedResponseMIMETypes []string `json:"SupportedResponseMIMETypes,omitempty"`

	// SupportedTransformInstanceTypes AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-algorithm-inferencespecification.html#cfn-sagemaker-algorithm-inferencespecification-supportedtransforminstancetypes
	SupportedTransformInstanceTypes []string `json:"SupportedTransformInstanceTypes,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *Algorithm_InferenceSpecification) AWSCloudFormationType() string {
	return "AWS::SageMaker::Algorithm.InferenceSpecification"
}
