// Code generated by "go generate". Please don't change this file directly.

package sagemaker

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// InferenceComponent_InferenceComponentSchedulingConfig AWS CloudFormation Resource (AWS::SageMaker::InferenceComponent.InferenceComponentSchedulingConfig)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-inferencecomponent-inferencecomponentschedulingconfig.html
type InferenceComponent_InferenceComponentSchedulingConfig struct {

	// AvailabilityZoneBalance AWS CloudFormation Property
	// Required: true
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-inferencecomponent-inferencecomponentschedulingconfig.html#cfn-sagemaker-inferencecomponent-inferencecomponentschedulingconfig-availabilityzonebalance
	AvailabilityZoneBalance *InferenceComponent_InferenceComponentAvailabilityZoneBalance `json:"AvailabilityZoneBalance"`

	// PlacementStrategy AWS CloudFormation Property
	// Required: true
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-inferencecomponent-inferencecomponentschedulingconfig.html#cfn-sagemaker-inferencecomponent-inferencecomponentschedulingconfig-placementstrategy
	PlacementStrategy string `json:"PlacementStrategy"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *InferenceComponent_InferenceComponentSchedulingConfig) AWSCloudFormationType() string {
	return "AWS::SageMaker::InferenceComponent.InferenceComponentSchedulingConfig"
}
