// Code generated by "go generate". Please don't change this file directly.

package sagemaker

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// HyperParameterTuningJob_ParameterRanges AWS CloudFormation Resource (AWS::SageMaker::HyperParameterTuningJob.ParameterRanges)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-hyperparametertuningjob-parameterranges.html
type HyperParameterTuningJob_ParameterRanges struct {

	// AutoParameters AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-hyperparametertuningjob-parameterranges.html#cfn-sagemaker-hyperparametertuningjob-parameterranges-autoparameters
	AutoParameters []HyperParameterTuningJob_AutoParametersItems `json:"AutoParameters,omitempty"`

	// CategoricalParameterRanges AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-hyperparametertuningjob-parameterranges.html#cfn-sagemaker-hyperparametertuningjob-parameterranges-categoricalparameterranges
	CategoricalParameterRanges []HyperParameterTuningJob_CategoricalParameterRangesItems `json:"CategoricalParameterRanges,omitempty"`

	// ContinuousParameterRanges AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-hyperparametertuningjob-parameterranges.html#cfn-sagemaker-hyperparametertuningjob-parameterranges-continuousparameterranges
	ContinuousParameterRanges []HyperParameterTuningJob_ContinuousParameterRangesItems `json:"ContinuousParameterRanges,omitempty"`

	// IntegerParameterRanges AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-hyperparametertuningjob-parameterranges.html#cfn-sagemaker-hyperparametertuningjob-parameterranges-integerparameterranges
	IntegerParameterRanges []HyperParameterTuningJob_IntegerParameterRangesItems `json:"IntegerParameterRanges,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *HyperParameterTuningJob_ParameterRanges) AWSCloudFormationType() string {
	return "AWS::SageMaker::HyperParameterTuningJob.ParameterRanges"
}
