// Code generated by "go generate". Please don't change this file directly.

package sagemaker

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// TrainingJob_ProfilerRuleConfiguration AWS CloudFormation Resource (AWS::SageMaker::TrainingJob.ProfilerRuleConfiguration)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-trainingjob-profilerruleconfiguration.html
type TrainingJob_ProfilerRuleConfiguration struct {

	// InstanceType AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-trainingjob-profilerruleconfiguration.html#cfn-sagemaker-trainingjob-profilerruleconfiguration-instancetype
	InstanceType *string `json:"InstanceType,omitempty"`

	// LocalPath AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-trainingjob-profilerruleconfiguration.html#cfn-sagemaker-trainingjob-profilerruleconfiguration-localpath
	LocalPath *string `json:"LocalPath,omitempty"`

	// RuleConfigurationName AWS CloudFormation Property
	// Required: true
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-trainingjob-profilerruleconfiguration.html#cfn-sagemaker-trainingjob-profilerruleconfiguration-ruleconfigurationname
	RuleConfigurationName string `json:"RuleConfigurationName"`

	// RuleEvaluatorImage AWS CloudFormation Property
	// Required: true
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-trainingjob-profilerruleconfiguration.html#cfn-sagemaker-trainingjob-profilerruleconfiguration-ruleevaluatorimage
	RuleEvaluatorImage string `json:"RuleEvaluatorImage"`

	// RuleParameters AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-trainingjob-profilerruleconfiguration.html#cfn-sagemaker-trainingjob-profilerruleconfiguration-ruleparameters
	RuleParameters map[string]string `json:"RuleParameters,omitempty"`

	// S3OutputPath AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-trainingjob-profilerruleconfiguration.html#cfn-sagemaker-trainingjob-profilerruleconfiguration-s3outputpath
	S3OutputPath *string `json:"S3OutputPath,omitempty"`

	// VolumeSizeInGB AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-trainingjob-profilerruleconfiguration.html#cfn-sagemaker-trainingjob-profilerruleconfiguration-volumesizeingb
	VolumeSizeInGB *int `json:"VolumeSizeInGB,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *TrainingJob_ProfilerRuleConfiguration) AWSCloudFormationType() string {
	return "AWS::SageMaker::TrainingJob.ProfilerRuleConfiguration"
}
