// Code generated by "go generate". Please don't change this file directly.

package serverless

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// Function_ProvisionedPollerConfig AWS CloudFormation Resource (AWS::Serverless::Function.ProvisionedPollerConfig)
// See: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
type Function_ProvisionedPollerConfig struct {

	// MaximumPollers AWS CloudFormation Property
	// Required: false
	// See: https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md
	MaximumPollers *int `json:"MaximumPollers,omitempty"`

	// MinimumPollers AWS CloudFormation Property
	// Required: false
	// See: https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md
	MinimumPollers *int `json:"MinimumPollers,omitempty"`

	// PollerGroupName AWS CloudFormation Property
	// Required: false
	// See: https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md
	PollerGroupName *string `json:"PollerGroupName,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *Function_ProvisionedPollerConfig) AWSCloudFormationType() string {
	return "AWS::Serverless::Function.ProvisionedPollerConfig"
}
