// Code generated by "go generate". Please don't change this file directly.

package emrserverless

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// JobRun_S3MonitoringConfiguration AWS CloudFormation Resource (AWS::EMRServerless::JobRun.S3MonitoringConfiguration)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-emrserverless-jobrun-s3monitoringconfiguration.html
type JobRun_S3MonitoringConfiguration struct {

	// LogUri AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-emrserverless-jobrun-s3monitoringconfiguration.html#cfn-emrserverless-jobrun-s3monitoringconfiguration-loguri
	LogUri *string `json:"LogUri,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *JobRun_S3MonitoringConfiguration) AWSCloudFormationType() string {
	return "AWS::EMRServerless::JobRun.S3MonitoringConfiguration"
}
