// Code generated by "go generate". Please don't change this file directly.

package emrserverless

import (
	"github.com/awslabs/goformation/v7/cloudformation/policies"
)

// JobRun_SparkSubmit AWS CloudFormation Resource (AWS::EMRServerless::JobRun.SparkSubmit)
// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-emrserverless-jobrun-sparksubmit.html
type JobRun_SparkSubmit struct {

	// EntryPoint AWS CloudFormation Property
	// Required: true
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-emrserverless-jobrun-sparksubmit.html#cfn-emrserverless-jobrun-sparksubmit-entrypoint
	EntryPoint string `json:"EntryPoint"`

	// EntryPointArguments AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-emrserverless-jobrun-sparksubmit.html#cfn-emrserverless-jobrun-sparksubmit-entrypointarguments
	EntryPointArguments []string `json:"EntryPointArguments,omitempty"`

	// SparkSubmitParameters AWS CloudFormation Property
	// Required: false
	// See: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-emrserverless-jobrun-sparksubmit.html#cfn-emrserverless-jobrun-sparksubmit-sparksubmitparameters
	SparkSubmitParameters *string `json:"SparkSubmitParameters,omitempty"`

	// AWSCloudFormationDeletionPolicy represents a CloudFormation DeletionPolicy
	AWSCloudFormationDeletionPolicy policies.DeletionPolicy `json:"-"`

	// AWSCloudFormationUpdateReplacePolicy represents a CloudFormation UpdateReplacePolicy
	AWSCloudFormationUpdateReplacePolicy policies.UpdateReplacePolicy `json:"-"`

	// AWSCloudFormationDependsOn stores the logical ID of the resources to be created before this resource
	AWSCloudFormationDependsOn []string `json:"-"`

	// AWSCloudFormationMetadata stores structured data associated with this resource
	AWSCloudFormationMetadata map[string]interface{} `json:"-"`

	// AWSCloudFormationCondition stores the logical ID of the condition that must be satisfied for this resource to be created
	AWSCloudFormationCondition string `json:"-"`
}

// AWSCloudFormationType returns the AWS CloudFormation resource type
func (r *JobRun_SparkSubmit) AWSCloudFormationType() string {
	return "AWS::EMRServerless::JobRun.SparkSubmit"
}
